version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nomi-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - arm64
      - amd64
      - "386"
      - ppc64le
    goarm:
      - "7"
    binary: nomi-cli
    main: ./cmd/cli
    ldflags:
      - "-X main.buildDate={{ .Date }}"
      - "-X main.buildVersion={{ .Tag }}"
    ignore:
      - goos: windows
        goarch: arm

checksum:
  algorithm: sha256
